Repository Consensys/gnark-crypto, pull requests merged in 2023-04, with the labels that each got.

#371 Eliminate 2 allocations per Pedersen call
  ecc/stark-curve/pedersen-hash/pedersen_hash.go
Labels: perf

#375 Refactor: final exponentiation in pairings
  ecc/bls12-377/internal/fptower/e12.go
  ecc/bls12-377/pairing.go
  ecc/bls12-378/internal/fptower/e12.go
  ecc/bls12-378/pairing.go
  ecc/bls12-381/internal/fptower/e12.go
  ecc/bls12-381/pairing.go
  ecc/bls24-315/internal/fptower/e24.go
  ecc/bls24-315/internal/fptower/e24_test.go
  ecc/bls24-315/pairing.go
  ecc/bls24-317/internal/fptower/asm.go
  ecc/bls24-317/internal/fptower/asm_noadx.go
  ecc/bls24-317/internal/fptower/e24.go
  ecc/bls24-317/internal/fptower/e24_test.go
  ecc/bls24-317/internal/fptower/e2_amd64.go
  ecc/bls24-317/internal/fptower/e2_fallback.go
  ecc/bls24-317/internal/fptower/e2_test.go
  ecc/bls24-317/pairing.go
  ecc/bn254/internal/fptower/e12.go
  ecc/bn254/pairing.go
  ecc/bw6-633/internal/fptower/e6.go
  ecc/bw6-633/internal/fptower/e6_test.go
  ecc/bw6-633/pairing.go
  ecc/bw6-756/internal/fptower/e6.go
  ecc/bw6-756/internal/fptower/e6_test.go
  ecc/bw6-756/pairing.go
  ecc/bw6-761/internal/fptower/e6.go
  ecc/bw6-761/internal/fptower/e6_test.go
  ecc/bw6-761/pairing.go
  internal/generator/tower/template/fq12over6over2/fq12.go.tmpl
Labels: cleanup, perf

#376 Refactor: export endomorphisms
  ecc/bls12-377/g1.go
  ecc/bls12-377/g1_test.go
  ecc/bls12-377/g2.go
  ecc/bls12-377/g2_test.go
  ecc/bls12-378/g1.go
  ecc/bls12-378/g1_test.go
  ecc/bls12-378/g2.go
  ecc/bls12-378/g2_test.go
  ecc/bls12-381/g1.go
  ecc/bls12-381/g1_test.go
  ecc/bls12-381/g2.go
  ecc/bls12-381/g2_test.go
  ecc/bls24-315/g1.go
  ecc/bls24-315/g1_test.go
  ecc/bls24-315/g2.go
  ecc/bls24-315/g2_test.go
  ecc/bls24-317/g1.go
  ecc/bls24-317/g1_test.go
  ecc/bls24-317/g2.go
  ecc/bls24-317/g2_test.go
  ecc/bn254/g1.go
  ecc/bn254/g1_test.go
  ecc/bn254/g2.go
  ecc/bn254/g2_test.go
  ecc/bw6-633/g1.go
  ecc/bw6-633/g1_test.go
  ecc/bw6-633/g2.go
  ecc/bw6-633/g2_test.go
  ecc/bw6-756/g1.go
  ecc/bw6-756/g1_test.go
  ecc/bw6-756/g2.go
  ecc/bw6-756/g2_test.go
  ecc/bw6-761/g1.go
  ecc/bw6-761/g1_test.go
  ecc/bw6-761/g2.go
  ecc/bw6-761/g2_test.go
  ecc/secp256k1/g1.go
  ecc/secp256k1/g1_test.go
  internal/generator/ecc/template/point.go.tmpl
  internal/generator/ecc/template/tests/point.go.tmpl
Labels: zk-evm

#374 fix(kzg): nb of digests in BatchVerifyMultiPoints should be nonzeo
  ecc/bls12-377/fr/kzg/kzg.go
  ecc/bls12-378/fr/kzg/kzg.go
  ecc/bls12-381/fr/kzg/kzg.go
  ecc/bls24-315/fr/kzg/kzg.go
  ecc/bls24-317/fr/kzg/kzg.go
  ecc/bn254/fr/kzg/kzg.go
  ecc/bw6-633/fr/kzg/kzg.go
  ecc/bw6-756/fr/kzg/kzg.go
  ecc/bw6-761/fr/kzg/kzg.go
  internal/generator/kzg/template/kzg.go.tmpl
Labels: bug

#380 Precompute point multiplication results in pedersen
  ecc/stark-curve/pedersen-hash/pedersen_hash.go
  ecc/stark-curve/pedersen-hash/pedersen_hash_test.go
Labels: perf

#386 Perf: KZG verification in a single point
  ecc/bls12-377/fr/kzg/kzg.go
  ecc/bls12-378/fr/kzg/kzg.go
  ecc/bls12-381/fr/kzg/kzg.go
  ecc/bls24-315/fr/kzg/kzg.go
  ecc/bls24-317/fr/kzg/kzg.go
  ecc/bn254/fr/kzg/kzg.go
  ecc/bw6-633/fr/kzg/kzg.go
  ecc/bw6-756/fr/kzg/kzg.go
  ecc/bw6-761/fr/kzg/kzg.go
  internal/generator/kzg/template/kzg.go.tmpl
Labels: perf

#385 feat: fix v computation in ECDSA signature
  ecc/bn254/ecdsa/ecdsa.go
  ecc/bn254/ecdsa/marshal.go
  ecc/secp256k1/ecdsa/ecdsa.go
  ecc/secp256k1/ecdsa/marshal.go
  ecc/stark-curve/ecdsa/ecdsa.go
  ecc/stark-curve/ecdsa/marshal.go
  internal/generator/ecdsa/template/ecdsa.go.tmpl
  internal/generator/ecdsa/template/marshal.go.tmpl
Labels: bug
