Repository Consensys/gnark-crypto, pull requests merged in 2023-03, with the labels that each got.

#347 feat: add ECDSA public key recover from message, signature and recovery info
  ecc/bls12-377/bls12-377.go
  ecc/bls12-377/ecdsa/ecdsa.go
  ecc/bls12-378/bls12-378.go
  ecc/bls12-378/ecdsa/ecdsa.go
  ecc/bls12-381/bls12-381.go
  ecc/bls12-381/ecdsa/ecdsa.go
  ecc/bls24-315/bls24-315.go
  ecc/bls24-315/ecdsa/ecdsa.go
  ecc/bls24-317/bls24-317.go
  ecc/bls24-317/ecdsa/ecdsa.go
  ecc/bn254/bn254.go
  ecc/bn254/ecdsa/ecdsa.go
  ecc/bn254/ecdsa/ecdsa_test.go
  ecc/bn254/ecdsa/marshal.go
  ecc/bw6-633/bw6-633.go
  ecc/bw6-633/ecdsa/ecdsa.go
  ecc/bw6-756/bw6-756.go
  ecc/bw6-756/ecdsa/ecdsa.go
  ecc/bw6-761/bw6-761.go
  ecc/bw6-761/ecdsa/ecdsa.go
  ecc/secp256k1/ecdsa/ecdsa.go
  ecc/secp256k1/ecdsa/ecdsa_test.go
  ecc/secp256k1/ecdsa/marshal.go
  ecc/secp256k1/secp256k1.go
  ecc/stark-curve/ecdsa/ecdsa.go
  ecc/stark-curve/ecdsa/ecdsa_test.go
  ecc/stark-curve/ecdsa/marshal.go
  ecc/stark-curve/stark_curve.go
  internal/generator/ecdsa/template/ecdsa.go.tmpl
  internal/generator/ecdsa/template/ecdsa.test.go.tmpl
  internal/generator/ecdsa/template/marshal.go.tmpl
Labels: new feature, zk-evm

#349 perf(stark-curve): no subgroup check on prime-order curve
  ecc/stark-curve/g1.go
Labels: perf

#351 perf(bw6-756): optimize GT subgroup membership
  ecc/bw6-756/internal/fptower/e6.go
Labels: perf

#356 Perf: optimize BLS24-317 final exp
  ecc/bls24-317/internal/fptower/e24_pairing.go
  ecc/bls24-317/pairing.go
Labels: perf

#360 Expose BLS12-381 tower
  ecc/bls12-381/bls12-381.go
Labels: consolidate

#363 fix: invalid infinity point decoding throws error
  ecc/bls12-377/marshal.go
  ecc/bls12-378/marshal.go
  ecc/bls12-381/marshal.go
  ecc/bls24-315/marshal.go
  ecc/bls24-317/marshal.go
  ecc/bn254/marshal.go
  ecc/bw6-633/marshal.go
  ecc/bw6-756/marshal.go
  ecc/bw6-761/marshal.go
  internal/generator/ecc/template/marshal.go.tmpl
Labels: bug

#366 Refactor: pairings
  ecc/bls12-377/internal/fptower/e12_pairing.go
  ecc/bls12-377/internal/fptower/e6.go
  ecc/bls12-377/pairing.go
  ecc/bls12-378/internal/fptower/e12_pairing.go
  ecc/bls12-378/internal/fptower/e6.go
  ecc/bls12-378/pairing.go
  ecc/bls12-381/internal/fptower/e12_pairing.go
  ecc/bls12-381/internal/fptower/e6.go
  ecc/bls12-381/pairing.go
  ecc/bls24-315/internal/fptower/e24_pairing.go
  ecc/bls24-315/pairing.go
  ecc/bls24-317/internal/fptower/e12.go
  ecc/bls24-317/internal/fptower/e24_pairing.go
  ecc/bls24-317/pairing.go
  ecc/bn254/internal/fptower/e12_pairing.go
  ecc/bn254/internal/fptower/e6.go
  ecc/bn254/pairing.go
  ecc/bw6-633/internal/fptower/e6_pairing.go
  ecc/bw6-633/pairing.go
  ecc/bw6-756/internal/fptower/e6_pairing.go
  ecc/bw6-756/pairing.go
  ecc/bw6-761/internal/fptower/e6_pairing.go
  ecc/bw6-761/pairing.go
  internal/generator/tower/template/fq12over6over2/fq6.go.tmpl
Labels: cleanup, perf, consolidate
