Repository Consensys/gnark-crypto, pull requests merged in 2023-10, with the labels that each got.

#451 Fix: GLV exponentiation in GT with large exponents
  ecc/bls12-377/g1.go
  ecc/bls12-377/g1_test.go
  ecc/bls12-377/g2.go
  ecc/bls12-377/g2_test.go
  ecc/bls12-377/internal/fptower/e12.go
  ecc/bls12-377/pairing_test.go
  ecc/bls12-378/g1.go
  ecc/bls12-378/g1_test.go
  ecc/bls12-378/g2.go
  ecc/bls12-378/g2_test.go
  ecc/bls12-378/internal/fptower/e12.go
  ecc/bls12-378/pairing_test.go
  ecc/bls12-381/g1.go
  ecc/bls12-381/g1_test.go
  ecc/bls12-381/g2.go
  ecc/bls12-381/g2_test.go
  ecc/bls12-381/internal/fptower/e12.go
  ecc/bls12-381/pairing_test.go
  ecc/bls24-315/g1.go
  ecc/bls24-315/g1_test.go
  ecc/bls24-315/g2.go
  ecc/bls24-315/g2_test.go
  ecc/bls24-315/internal/fptower/e24.go
  ecc/bls24-315/pairing_test.go
  ecc/bls24-317/g1.go
  ecc/bls24-317/g1_test.go
  ecc/bls24-317/g2.go
  ecc/bls24-317/g2_test.go
  ecc/bls24-317/internal/fptower/e24.go
  ecc/bls24-317/pairing_test.go
  ecc/bn254/g1.go
  ecc/bn254/g1_test.go
  ecc/bn254/g2.go
  ecc/bn254/g2_test.go
  ecc/bn254/internal/fptower/e12.go
  ecc/bn254/pairing_test.go
  ecc/bw6-633/g1.go
  ecc/bw6-633/g1_test.go
  ecc/bw6-633/g2.go
  ecc/bw6-633/g2_test.go
  ecc/bw6-633/internal/fptower/e6.go
  ecc/bw6-633/pairing_test.go
  ecc/bw6-756/g1.go
  ecc/bw6-756/g1_test.go
  ecc/bw6-756/g2.go
  ecc/bw6-756/g2_test.go
  ecc/bw6-756/internal/fptower/e6.go
  ecc/bw6-756/pairing_test.go
  ecc/bw6-761/g1.go
  ecc/bw6-761/g1_test.go
  ecc/bw6-761/g2.go
  ecc/bw6-761/g2_test.go
  ecc/bw6-761/internal/fptower/e6.go
  ecc/bw6-761/pairing_test.go
  ecc/secp256k1/g1.go
  ecc/secp256k1/g1_test.go
  internal/generator/ecc/template/point.go.tmpl
  internal/generator/ecc/template/tests/point.go.tmpl
  internal/generator/pairing/template/tests/pairing.go.tmpl
  internal/generator/tower/template/fq12over6over2/fq12.go.tmpl
Labels: bug, cleanup

#446 perf(fft): introduce cache efficient bit reverse shuffling
  ecc/bls12-377/fr/fft/bitreverse.go
  ecc/bls12-377/fr/fft/bitreverse_test.go
  ecc/bls12-377/fr/fft/fft.go
  ecc/bls12-377/fr/fft/fft_test.go
  ecc/bls12-378/fr/fft/bitreverse.go
  ecc/bls12-378/fr/fft/bitreverse_test.go
  ecc/bls12-378/fr/fft/fft.go
  ecc/bls12-378/fr/fft/fft_test.go
  ecc/bls12-381/fr/fft/bitreverse.go
  ecc/bls12-381/fr/fft/bitreverse_test.go
  ecc/bls12-381/fr/fft/fft.go
  ecc/bls12-381/fr/fft/fft_test.go
  ecc/bls24-315/fr/fft/bitreverse.go
  ecc/bls24-315/fr/fft/bitreverse_test.go
  ecc/bls24-315/fr/fft/fft.go
  ecc/bls24-315/fr/fft/fft_test.go
  ecc/bls24-317/fr/fft/bitreverse.go
  ecc/bls24-317/fr/fft/bitreverse_test.go
  ecc/bls24-317/fr/fft/fft.go
  ecc/bls24-317/fr/fft/fft_test.go
  ecc/bn254/fr/fft/bitreverse.go
  ecc/bn254/fr/fft/bitreverse_test.go
  ecc/bn254/fr/fft/fft.go
  ecc/bn254/fr/fft/fft_test.go
  ecc/bw6-633/fr/fft/bitreverse.go
  ecc/bw6-633/fr/fft/bitreverse_test.go
  ecc/bw6-633/fr/fft/fft.go
  ecc/bw6-633/fr/fft/fft_test.go
  ecc/bw6-756/fr/fft/bitreverse.go
  ecc/bw6-756/fr/fft/bitreverse_test.go
  ecc/bw6-756/fr/fft/fft.go
  ecc/bw6-756/fr/fft/fft_test.go
  ecc/bw6-761/fr/fft/bitreverse.go
  ecc/bw6-761/fr/fft/bitreverse_test.go
  ecc/bw6-761/fr/fft/fft.go
  ecc/bw6-761/fr/fft/fft_test.go
  internal/generator/fft/generate.go
  internal/generator/fft/template/bitreverse.go.tmpl
  internal/generator/fft/template/fft.go.tmpl
  internal/generator/fft/template/tests/bitreverse.go.tmpl
  internal/generator/fft/template/tests/fft.go.tmpl
  internal/generator/main.go
Labels: perf, zk-evm

#459 Perf: faster final exponentiation (hard part) for BW6 curves
  ecc/bw6-633/bw6-633.go
  ecc/bw6-633/internal/fptower/e6_pairing.go
  ecc/bw6-633/pairing.go
  ecc/bw6-756/bw6-756.go
  ecc/bw6-756/internal/fptower/e6_pairing.go
  ecc/bw6-756/pairing.go
  ecc/bw6-761/bw6-761.go
  ecc/bw6-761/internal/fptower/e6_pairing.go
  ecc/bw6-761/pairing.go
Labels: perf

#465 Refactor(BW6): use revisited Ate pairing instead of Tate
  ecc/bw6-633/g1.go
  ecc/bw6-756/g1.go
  ecc/bw6-756/g2.go
  ecc/bw6-756/internal/fptower/e3.go
  ecc/bw6-756/internal/fptower/e6_pairing.go
  ecc/bw6-756/pairing.go
  ecc/bw6-761/g1.go
  ecc/bw6-761/g2.go
  ecc/bw6-761/internal/fptower/e3.go
  ecc/bw6-761/internal/fptower/e6_pairing.go
  ecc/bw6-761/pairing.go
  internal/generator/config/bw6-756.go
  internal/generator/config/bw6-761.go
  internal/generator/ecc/template/point.go.tmpl
Labels: cleanup, consolidate
