Repository Consensys/gnark-crypto, pull requests merged in 2024-10, with the labels that each got.

#549 chore: use golint option to include generated files
  .github/workflows/pr.yml
  .github/workflows/push.yml
  .golangci.yml
Labels: cleanup

#543 Feat: Eisenstein integers
  field/eisenstein/doc.go
  field/eisenstein/eisenstein.go
  field/eisenstein/eisenstein_test.go
Labels: new feature

#551 fix: buffer sufficient size
  ecc/bls12-377/shplonk/shplonk.go
  ecc/bls12-381/shplonk/shplonk.go
  ecc/bls24-315/shplonk/shplonk.go
  ecc/bls24-317/shplonk/shplonk.go
  ecc/bn254/shplonk/shplonk.go
  ecc/bw6-633/shplonk/shplonk.go
  ecc/bw6-761/shplonk/shplonk.go
  internal/generator/shplonk/template/shplonk.go.tmpl
Labels: bug

#557 perf: subgroup check
  ecc/bls12-377/g1.go
  ecc/bls12-377/g1_test.go
  ecc/bls12-377/g2.go
  ecc/bls12-377/g2_test.go
  ecc/bls12-381/g1.go
  ecc/bls12-381/g1_test.go
  ecc/bls12-381/g2.go
  ecc/bls12-381/g2_test.go
  ecc/bls24-315/g1.go
  ecc/bls24-315/g1_test.go
  ecc/bls24-315/g2.go
  ecc/bls24-315/g2_test.go
  ecc/bls24-317/g1.go
  ecc/bls24-317/g1_test.go
  ecc/bls24-317/g2.go
  ecc/bls24-317/g2_test.go
  ecc/bn254/g1_test.go
  ecc/bn254/g2.go
  ecc/bn254/g2_test.go
  ecc/bw6-633/g1.go
  ecc/bw6-633/g1_test.go
  ecc/bw6-633/g2.go
  ecc/bw6-633/g2_test.go
  ecc/bw6-761/g1.go
  ecc/bw6-761/g1_test.go
  ecc/bw6-761/g2.go
  ecc/bw6-761/g2_test.go
  ecc/secp256k1/g1_test.go
  internal/generator/ecc/template/point.go.tmpl
  internal/generator/ecc/template/tests/point.go.tmpl
Labels: perf
