Repository Consensys/gnark-crypto, pull requests merged in 2025-01, with the labels that each got.

#608 feat(bw6-761): Miller loop using direct sextic extension
  ecc/bw6-761/internal/fptower/e6_direct.go
  ecc/bw6-761/internal/fptower/e6_direct_test.go
  ecc/bw6-761/pairing.go
  ecc/bw6-761/pairing_test.go
  internal/generator/pairing/template/tests/pairing.go.tmpl
Labels: zk-evm

#592 docs: readme
  README.md
Labels: typo

#605 chore: fix problematic function name in comment
  field/generator/config/fft_config.go
Labels: typo

#610 typos: squashed typo fixes
  README.md
  field/generator/config/fft_config.go
Labels: typo

#615 Perf: Parallelize subgroup checks in KZG MPC setup
  ecc/bls12-377/kzg/mpcsetup.go
  ecc/bls12-381/kzg/mpcsetup.go
  ecc/bls24-315/kzg/mpcsetup.go
  ecc/bls24-317/kzg/mpcsetup.go
  ecc/bn254/kzg/mpcsetup.go
  ecc/bw6-633/kzg/mpcsetup.go
  ecc/bw6-761/kzg/mpcsetup.go
  internal/generator/kzg/template/mpcsetup.go.tmpl
  utils/parallel.go
Labels: perf
